### ISSUE TITLE
Can't connect to the download site

### ISSUE THREAD

**Issue by T-727** [vktec/slimy#2]
https://ci.vktec.org.uk/slimy/main/files/slimy-windows-amd64.exe

> We can’t connect to the server at ci.vktec.org.uk.

**Comment by AI-nsley69** [comment]
Currently, vk has provided a Windows build pinned in the #slimy channel on [their discord server](https://discord.com/channels/713120848835510293/796792644918312962/840926663268368434)

**Comment by silversquirl** [comment]
Yeah, the CI's not working currently, sorry about that. I should really fix it, or at least edit the link out of the readme

**Comment by T-727** [comment]
yeah I don't have any use need for the program at the moment, just thought I'd point it out :)
