### ISSUE TITLE
GL_INVALID_VALUE in glGetBufferSubData

### ISSUE THREAD

**Issue by devjta** [vktec/slimy#3]
When I want to search my seed, which is negative, it doesnt work..

The program thinks its some sort of options, as it starts with -.

./slimy -f human '-3918415846381416534' 5000 5
flag provided but not defined: -3918415846381416534

./slimy -f human "-3918415846381416534" 5000 5
flag provided but not defined: -3918415846381416534

./slimy -f human -3918415846381416534 5000 5
flag provided but not defined: -3918415846381416534

But if I remove the "-" before, it crashes anyway:
`./slimy -f human "3918415846381416534" 5000 5
Searching (-5000, -5000) to (5000, 5000)
2021/11/16 11:02:57 GL debug: 6 [MED] API Performance: CPU mapping a busy "bufferobj" BO stalled and took 352.215 ms.

panic: 7 [HIGH] API Error: GL_INVALID_VALUE in glGetBufferSubData(offset 0 + size 16777024 > buffer size 12582912)

goroutine 1 [running, locked to thread]:
github.com/vktec/gldebug.MessageCallback(0x8246, 0x824c, 0x7, 0x9146, {0xc001186000, 0x57})
	/home/jota/go/pkg/mod/github.com/vktec/gldebug@v0.0.0-20210121173738-c8c0d4d4bf50/debug.go:64 +0x3d4
github.com/vktec/gll.gllDebugProc(0x0, 0x0, 0x0, 0x0, 0x57, 0x0, 0x0)
	/home/jota/go/pkg/mod/github.com/vktec/gll@v0.0.0-20210115000034-d6509ba05bcf/debug.go:76 +0x73
github.com/vktec/gll._Cfunc_gllCall_glGetBufferSubData(0x7fa1ec6b2f00, 0x90d2, 0x0, 0xffff40, 0xc000180000)
	_cgo_gotypes.go:14299 +0x45
github.com/vktec/gll.(*lib).GetBufferSubData.func1(0x97, 0x600980, 0xc00000e0a8, 0x600980, 0xc00000e0a8)
	/home/jota/go/pkg/mod/github.com/vktec/gll@v0.0.0-20210115000034-d6509ba05bcf/gl.go:12422 +0x99
github.com/vktec/gll.(*lib).GetBufferSubData(0x600980, 0xe0a8, 0xffff4, 0xc000129c10, 0xc000129c18)
	/home/jota/go/pkg/mod/github.com/vktec/gll@v0.0.0-20210115000034-d6509ba05bcf/gl.go:12422 +0x19
github.com/vktec/slimy/gpu.(*Searcher).executeSearch(0xc000012360, 0xffffec70, 0xffffec70, 0xfffff070, 0xfffff070)
	/home/jota/go/pkg/mod/github.com/vktec/slimy@v0.0.0-20210307114243-978b898fade0/gpu/search.go:234 +0x1f5
github.com/vktec/slimy/gpu.(*Searcher).Search(0xc000012360, 0xffffec78, 0xffffec78, 0x1388, 0x1388, 0x5, 0x366102739dd37056)
	/home/jota/go/pkg/mod/github.com/vktec/slimy@v0.0.0-20210307114243-978b898fade0/gpu/search.go:192 +0x693
main.runSearch({0x709ac0, 0xc000012360}, 0x69dfa4, 0x0, 0x0, 0x0, 0x6ae9de, 0x1c)
	/home/jota/go/pkg/mod/github.com/vktec/slimy@v0.0.0-20210307114243-978b898fade0/cmd/slimy/main.go:68 +0x173
main.main()
	/home/jota/go/pkg/mod/github.com/vktec/slimy@v0.0.0-20210307114243-978b898fade0/cmd/slimy/main.go:184 +0x945
`

**Comment by silversquirl** [comment]
`./slimy -- -3918415846381416534 5000 5`

I'm not certain why it's crashing, but you can try using the CPU search: `./slimy -m cpu -- -3918415846381416534 5000 5`

Or just use web slimy: https://vktec.org.uk/slimy-zig/

**Comment by silversquirl** [comment]
Ah, looks like this is me forgetting to bounds check the results. A threshold of 5 is ridiculously low, try something like 30 instead

**Comment by devjta** [comment]
Thanks for help for the -- to get my negative seed working.

And the other 2 ideas also worked fine. So either have it 30 or use the CPU flag. Thanks for the fast response :)

**Comment by silversquirl** [comment]
Should be fixed now :)
